In [1]:
pip install opencv-python

Note: you may need to restart the kernel to use updated packages.


In [10]:
import cv2

# IMAGE READING

In [11]:
img=cv2.imread("download.jpg")

In [12]:
img

array([[[ 46,  31,   0],
        [ 46,  31,   0],
        [ 46,  31,   0],
        ...,
        [138,  93,  49],
        [138,  93,  49],
        [138,  93,  49]],

       [[ 47,  32,   0],
        [ 46,  31,   0],
        [ 46,  31,   0],
        ...,
        [138,  93,  49],
        [138,  93,  49],
        [138,  93,  49]],

       [[ 48,  33,   0],
        [ 47,  32,   0],
        [ 47,  32,   0],
        ...,
        [138,  93,  49],
        [138,  93,  49],
        [138,  93,  49]],

       ...,

       [[108,  81,  71],
        [108,  81,  71],
        [106,  81,  71],
        ...,
        [191, 154, 120],
        [191, 154, 120],
        [191, 154, 120]],

       [[106,  80,  68],
        [106,  80,  68],
        [106,  80,  68],
        ...,
        [189, 152, 118],
        [189, 152, 118],
        [189, 152, 118]],

       [[105,  79,  65],
        [105,  79,  65],
        [105,  79,  67],
        ...,
        [185, 148, 114],
        [185, 148, 114],
        [185, 148, 114]]

In [5]:
grey=cv2.imread("download.jpg",0)

In [6]:
grey

array([[ 23,  23,  23, ...,  85,  85,  85],
       [ 24,  23,  23, ...,  85,  85,  85],
       [ 25,  24,  24, ...,  85,  85,  85],
       ...,
       [ 81,  81,  81, ..., 148, 148, 148],
       [ 79,  79,  79, ..., 146, 146, 146],
       [ 78,  78,  78, ..., 142, 142, 142]], dtype=uint8)

In [ ]:
cv2.imshow("colour image",img)
cv2.imshow("greyscale image",grey)
cv2.waitKey(0)
cv2.destroyAllWindows()



## IMAGE WRITING

In [8]:
cv2.imwrite('C:/Users/admin/minions.jpg',img)

True

In [13]:
import numpy as nump

# IMAGE SHAPE

In [14]:
shape=img.shape

In [15]:
print(shape)

(168, 300, 3)


# IMAGE SIZE

In [16]:
size=img.size

In [17]:
print(size)

151200


# VALUE OF PIXEL

In [18]:
pixel=img[123,299]

In [19]:
print(pixel)

[199 156  99]


# Region Of Interest